# Generated by Django 3.0.2 on 2020-03-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdHakimaru', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Objetos',
            },
        ),
    ]
