# Generated by Django 3.0.2 on 2020-03-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdHakimaru', '0002_objeto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objeto',
            name='estado',
        ),
        migrations.AddField(
            model_name='objeto',
            name='origen',
            field=models.CharField(choices=[('Robo', 'Robo'), ('Compra', 'Compra'), ('Regalo', 'Regalo')], default='Robo', max_length=20),
        ),
    ]
